services:
  api:
    build:
      context: ./housing/api
      dockerfile: Dockerfile
    image: johnbritto1260/housing-api:latest
    environment:
      - MLFLOW_TRACKING_URI=http://192.168.0.105:5000
    ports:
      - "5001:5001"

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    depends_on:
      - api
