[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "housing"
version = "0.1.0"
dependencies = [
    "fastapi",
    "uvicorn",
    "scikit-learn",
    "pandas",
    "mlflow",
    "joblib",
    "pytest",
    "flake8"
]
