FROM python:3.10-slim

# Set working directory
WORKDIR /app

# Copy requirements and install
COPY requirements.txt .
RUN pip install --no-cache-dir \
    -i https://pypi.org/simple \
    --extra-index-url https://mirrors.aliyun.com/pypi/simple \
    -r requirements.txt

# Copy the app code
COPY . .

# Expose port
EXPOSE 5001

# Run the Flask app
CMD ["python3", "main.py"]